In [1]:
import dgl
import torch
import os, pickle
import numpy as np
import torch.nn as nn
from dgl.nn import GraphConv

In [2]:
g = dgl.DGLGraph()

/Users/kiarash/projects/zachary_club/venv/lib/python3.9/site-packages/dgl/base.py:45: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  return warnings.warn(message, category=category, stacklevel=1)


In [3]:
with open(os.path.join('data', 'edge_list.pickle'), 'rb') as f:
    edge_list = pickle.load(f)
    edge_list = [[int(x[0]), int(x[1])] for x in edge_list]

In [4]:
g = dgl.DGLGraph()
g.add_nodes(34)
src, dst = tuple(zip(*edge_list))
g.add_edges(src, dst)
g.add_edges(dst, src)

In [58]:
def agg_func(edges):
    return {'m': edges.src['h']}

In [81]:
def agg_func2(nodes):
    # print(help(nodes))
    return {'h': torch.sum(nodes.mailbox['m'], dim=1)}

In [91]:
g.ndata['h'] = torch.ones(34)

In [92]:
linear = nn.Parameter(torch.FloatTensor(size=(1, 34 * 2)))

# g.apply_edges(agg_func)
# g.apply_nodes(agg_func2)
g.send_and_recv(g.edges(), message_func=agg_func, reduce_func=agg_func2)
# g.edata['out'] = g.edata['h'] * linear
g.ndata['h']

tensor([16.,  9., 10.,  6.,  3.,  4.,  4.,  4.,  5.,  2.,  3.,  1.,  2.,  5.,
         2.,  2.,  2.,  2.,  2.,  3.,  2.,  2.,  2.,  5.,  3.,  3.,  2.,  4.,
         3.,  4.,  4.,  6., 12., 17.])

In [53]:
torch.sum(torch.ones(156, 3), dim=1)

tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [47]:
torch.ones(156).shape

torch.Size([156])

In [52]:
torch.ones(156, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1